In [125]:
import torch
import math

In [126]:

X = torch.randn(256)

In [127]:
ground_truth = torch.exp(X-X.max()) / torch.exp(X-X.max()).sum()
print(ground_truth)

tensor([2.7278e-03, 9.7951e-04, 1.1875e-03, 2.3093e-03, 1.4092e-03, 5.7963e-03,
        2.4905e-03, 1.0308e-03, 8.6299e-03, 1.3255e-03, 2.1113e-03, 4.3850e-03,
        1.4579e-03, 1.2460e-03, 1.5303e-03, 6.5837e-04, 1.2620e-03, 2.1632e-03,
        2.5061e-03, 9.5478e-03, 1.3501e-03, 1.0172e-02, 3.6166e-02, 6.2668e-03,
        2.3637e-03, 4.7929e-03, 1.7189e-03, 3.7752e-03, 2.0311e-03, 3.1141e-03,
        4.0896e-03, 1.4601e-03, 3.9749e-03, 1.7208e-02, 6.7663e-03, 3.8070e-03,
        1.8211e-03, 3.0130e-03, 6.7097e-03, 5.3765e-04, 9.8571e-04, 2.5792e-03,
        5.8088e-04, 1.0993e-03, 1.3862e-02, 6.9118e-03, 1.5507e-02, 1.6613e-03,
        7.9623e-03, 3.2208e-03, 1.9265e-03, 2.3472e-03, 1.8921e-03, 9.8892e-03,
        4.2900e-03, 2.6016e-03, 1.8226e-03, 8.4242e-03, 9.5174e-04, 4.9633e-03,
        7.0350e-04, 8.8302e-03, 1.3671e-03, 1.0156e-02, 8.6029e-04, 5.0059e-03,
        2.4312e-03, 5.3595e-04, 5.9013e-04, 1.8752e-03, 3.2629e-03, 3.0918e-03,
        2.1107e-03, 4.4523e-03, 1.0150e-03, 9.8541e-04, 2.8177e-03, 1.7277e-03,
        4.9750e-03, 1.7436e-03, 2.3593e-03, 2.4758e-03, 1.2806e-03, 1.6628e-03,
        1.4616e-02, 2.7872e-04, 3.5037e-03, 7.8836e-03, 1.0472e-03, 2.0209e-03,
        1.3435e-03, 1.9997e-03, 2.2199e-03, 8.7710e-04, 1.4469e-03, 1.0256e-03,
        7.3762e-05, 2.6149e-03, 1.6761e-03, 3.6261e-03, 1.4808e-03, 1.6168e-03,
        1.0901e-03, 9.2691e-03, 8.1332e-03, 1.5820e-03, 1.3692e-03, 1.4557e-03,
        8.0928e-03, 9.6484e-03, 1.8758e-03, 1.8115e-03, 3.5242e-03, 4.7058e-04,
        1.8272e-03, 2.1950e-02, 5.1273e-04, 5.1879e-03, 1.4589e-03, 1.1666e-03,
        3.0689e-03, 1.9141e-03, 2.1647e-03, 1.0434e-03, 2.8031e-03, 1.1630e-03,
        1.8295e-03, 3.2310e-03, 6.2370e-03, 1.4200e-03, 1.0230e-03, 2.0089e-03,
        1.5495e-03, 2.1222e-03, 2.0888e-03, 4.3751e-03, 1.2270e-03, 3.1880e-03,
        5.0257e-03, 5.4528e-04, 7.5410e-03, 2.1704e-03, 5.3805e-03, 1.7737e-03,
        7.4413e-03, 2.0585e-03, 4.5556e-03, 7.9495e-04, 3.7904e-03, 2.2428e-03,
        8.6594e-04, 6.5747e-03, 1.3776e-03, 9.3038e-04, 7.3441e-03, 3.5972e-03,
        1.2152e-03, 5.1727e-04, 1.7770e-03, 3.4995e-03, 1.3624e-02, 1.6583e-03,
        9.9967e-03, 7.3970e-04, 2.1117e-02, 1.8859e-03, 2.7336e-03, 2.2055e-03,
        1.4504e-03, 3.3200e-03, 1.8688e-03, 2.7407e-03, 6.2584e-04, 1.2560e-02,
        4.8169e-03, 1.1238e-03, 5.3523e-03, 8.0058e-03, 6.6113e-04, 1.6834e-03,
        1.9350e-02, 2.8838e-03, 2.0368e-03, 3.0039e-03, 7.5243e-03, 2.0190e-02,
        1.7746e-02, 3.7652e-03, 6.7328e-03, 2.6071e-03, 2.5213e-03, 7.5022e-04,
        1.0250e-02, 8.4815e-03, 2.0921e-03, 1.1326e-02, 1.0964e-03, 1.1758e-03,
        5.9830e-03, 2.7523e-03, 2.4626e-03, 5.3781e-03, 7.7968e-04, 2.0297e-03,
        4.0720e-03, 2.1088e-03, 1.2128e-03, 5.1451e-04, 1.9766e-03, 6.4895e-03,
        1.3522e-03, 7.1332e-04, 6.4894e-04, 8.3827e-04, 2.9361e-03, 2.6965e-03,
        9.4196e-04, 3.5005e-03, 3.7397e-03, 3.7702e-03, 4.9029e-03, 3.4333e-04,
        2.3429e-03, 4.2895e-03, 6.9277e-03, 4.1071e-04, 6.9466e-04, 2.5784e-03,
        8.8763e-04, 4.1872e-04, 1.0700e-03, 1.9523e-03, 1.4162e-03, 3.6430e-03,
        1.3686e-03, 7.9239e-03, 1.2766e-02, 6.6823e-03, 2.7452e-03, 1.9477e-03,
        2.2380e-03, 1.7636e-04, 7.4933e-03, 2.9415e-03, 2.5347e-03, 6.0113e-03,
        7.2143e-03, 1.1278e-02, 2.1535e-03, 1.4381e-03, 2.4671e-03, 7.1914e-03,
        1.4348e-02, 7.1015e-03, 2.0603e-03, 4.9865e-04])

# 2-pass online-softmax
只需要扫描两次，就可以得到softmax的结果。第一次是计算分母部分的求和。第二次是计算每个元素的softmax值。

In [128]:
X_block = torch.split(X, split_size_or_sections=4)

def dfs(X_block, l, r):
    if l == r:
        block_mx = X_block[l].max()
        block_sum = torch.exp(X_block[l] - block_mx).sum()
        return block_mx, block_sum
    mid = (l + r) // 2
    left_mx, left_sum = dfs(X_block, l, mid)
    right_mx, right_sum = dfs(X_block, mid + 1, r)
    block_mx = max(left_mx, right_mx)
    block_sum = left_sum * math.exp(left_mx-block_mx) + right_sum * math.exp(right_mx-block_mx)
    return block_mx, block_sum

block_mx, block_sum = dfs(X_block, 0, len(X_block) - 1)
block_softmax = torch.exp(X - block_mx) / block_sum
assert torch.allclose(block_softmax, ground_truth)


# 2-pass self-attention

这里结合一些KV cache的trick，可以得到一个2-pass的self-attention。

In [130]:
# (batch size, sequence length, hidden size)
# 这里这考虑单个head的情况
b, s, h = 2, 10, 4
K, V = torch.randn(b, s, h), torch.randn(b, s, h)
Q = torch.randn(b, 1, h) # 这里只考虑单个query

ground_truth = torch.softmax(Q @ K.transpose(-1, -2) / math.sqrt(h), dim=-1) @ V
print(ground_truth.shape)
print(ground_truth)

torch.Size([2, 1, 4])

tensor([[[-0.7168,  0.8399,  0.0859,  0.1067]],

        [[ 0.5376, -0.2856, -0.4897,  0.2870]]])

In [131]:
# * the first pass
mx, d = None, None
# shape of x: (b, 1, s)
# shape of mx: (b, 1, 1)
# shape of d: (b, 1, 1)
x = torch.zeros(b, 1, s)
for i in range(s):
    x[:, :, i:i+1] = Q @ K[..., i:i+1, :].transpose(-1, -2) / math.sqrt(h) # (b, 1, d) @ (b, d, 1) -> (b, 1, 1)
    if i == 0:
        mx = x[:, :, 0:1]
        d = torch.ones_like(mx)
    else:
        new_mx = torch.max(mx, x[:, :, i:i+1])
        d = d * torch.exp(mx-new_mx) + torch.exp(x[:, :, i:i+1]-new_mx)
        mx = new_mx

# * the second pass
# shape of d: (b, 1, 1)
att = torch.exp(x-mx) / d
# shape of att: (b, 1, s)
# shape of V: (b, s, d)
output = att @ V
print(output)
# shape of output: (b, 1, d)
assert torch.allclose(output, ground_truth)


tensor([[[-0.7168,  0.8399,  0.0859,  0.1067]],

        [[ 0.5376, -0.2856, -0.4897,  0.2870]]])

# One-pass self-attention
注意，在one-pass self-attention中，每次只处理K上的一个新元素，但是其实可以处理K上的一个block。

In [200]:

# * the first pass
x = torch.zeros(b, 1, s)
mx, d, o = None, None, None
# shape of x: (b, 1, s)
# shape of mx: (b, 1, 1)
# shape of d: (b, 1, 1)
# shape of o: (b, 1, d)
for i in range(s):
    x[:, :, i:i+1] = Q @ K[..., i:i+1, :].transpose(-1, -2) / math.sqrt(h) # (b, 1, d) @ (b, d, 1) -> (b, 1, 1)
    if i == 0:
        mx = x[:, :, 0:1]
        d = torch.ones_like(mx)
        o = V[..., i:i+1, :]
    else:
        new_mx = torch.max(mx, x[:, :, i:i+1])
        new_d = d * torch.exp(mx-new_mx) + torch.exp(x[:, :, i:i+1]-new_mx)
        o = o * d / new_d * torch.exp(mx - new_mx) + V[..., i:i+1, :] * torch.exp(x[:, :, i:i+1] - new_mx) / new_d
        mx = new_mx
        d = new_d

output = o
print(output)
# shape of output: (b, 1, d)
assert torch.allclose(output, ground_truth)


╭─────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮
│ /var/folders/nx/yz5n2z3176q0dm5gd74skwjr0000gn/T/ipykernel_69533/298007217.py:9 in <module>                     │
│                                                                                                                 │
│ [Errno 2] No such file or directory:                                                                            │
│ '/var/folders/nx/yz5n2z3176q0dm5gd74skwjr0000gn/T/ipykernel_69533/298007217.py'                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: expand(torch.FloatTensor{[2, 4, 8, 1]}, size=[2, 1, 1]): the number of sizes provided (3) must be 
greater or equal to the number of dimensions in the tensor (4)

# Flash attention V1


In [211]:
# 如果q_len=1，其实就是KV cache技巧下的情况
batch_size, num_heads, q_len, kv_len, head_dim = 2, 4, 8, 16, 10
q_block_size = 4
kv_block_size = 8
num_row_tiles = q_len // q_block_size
num_col_tiles = kv_len // kv_block_size

print(f"num_row_tiles: {num_row_tiles}")
print(f"num_col_tiles: {num_col_tiles}")


num_row_tiles: 2

num_col_tiles: 2

In [216]:

Q = torch.randn(batch_size, num_heads, q_len, head_dim, requires_grad=True)
K = torch.randn(batch_size, num_heads, kv_len, head_dim, requires_grad=True)
V = torch.randn(batch_size, num_heads, kv_len, head_dim, requires_grad=True)
O = torch.zeros_like(Q)
# [..., None] 是最后一个维度上增加一个维度的有效操作
m = torch.ones(Q.shape[:-1])[..., None] * -float('inf') # shape: (b, h, q_len, 1)
d = torch.zeros(Q.shape[:-1])[..., None] # shape: (b, h, q_len, 1)

# 这里省略了mask，实际上如果是使用KV cache技巧，只需要考虑q_len=1的情况，这个时候实际上已经考虑mask了
ground_truth = torch.softmax(Q @ K.transpose(-1, -2) / math.sqrt(head_dim), dim=-1) @ V
print(Q.shape)
print(ground_truth.shape)
assert Q.shape == ground_truth.shape

torch.Size([2, 4, 8, 10])

torch.Size([2, 4, 8, 10])

In [217]:
Q_blocks = torch.split(Q, split_size_or_sections=q_block_size, dim=-2)
K_blocks = torch.split(K, split_size_or_sections=kv_block_size, dim=-2)
V_blocks = torch.split(V, split_size_or_sections=kv_block_size, dim=-2)
O_blocks = list(torch.split(O, split_size_or_sections=q_block_size, dim=-2)) # make it into a list, coz tuple assignment is not supported
m_blocks = torch.split(m, split_size_or_sections=q_block_size, dim=-2)
d_blocks = torch.split(d, split_size_or_sections=q_block_size, dim=-2)

for i in range(num_row_tiles):
    Qi = Q_blocks[i] # shape: (b, h, q_block_size, head_dim)

    oi = O_blocks[i] # shape: (b, h, q_block_size, head_dim)
    mi = m_blocks[i] # shape: (b, h, q_block_size, 1)
    di = d_blocks[i] # shape: (b, h, q_block_size, 1)

    for j in range(num_col_tiles):
        Kj = K_blocks[j] # shape: (b, h, kv_block_size, head_dim)
        Vj = V_blocks[j] # shape: (b, h, kv_block_size, head_dim)

        S_ij = Qi @ Kj.transpose(-1, -2) / math.sqrt(head_dim) # shape: (b, h, q_block_size, kv_block_size)
        m_ij = torch.max(S_ij, dim=-1, keepdim=True).values # shape: (b, h, q_block_size, 1)
        d_ij = torch.exp(S_ij-m_ij).sum(dim=-1, keepdim=True) # shape: (b, h, q_block_size, 1)
        P_ij = torch.exp(S_ij-m_ij) / d_ij # shape: (b, h, q_block_size, kv_block_size)
        o_ij = P_ij @ Vj # (b, h, q_block_size, head_dim)

        new_mi = torch.maximum(mi, m_ij) # shape: (b, h, q_block_size, 1)
        new_di = di * torch.exp(mi - new_mi) + d_ij * torch.exp(m_ij - new_mi) # shape: (b, h, q_block_size, 1)
        new_oi = oi * di / new_di * torch.exp(mi - new_mi) + o_ij * d_ij / new_di * torch.exp(m_ij - new_mi) # shape: (b, h, q_block_size, head_dim)

        mi = new_mi
        di = new_di
        oi = new_oi

    O_blocks[i] = oi # shape: (b, h, q_block_size, head_dim)

O = torch.cat(O_blocks, dim=-2) # shape: (b, h, q_len, head_dim)
print(O.shape)
assert torch.allclose(O, ground_truth, atol=1e-5)




torch.Size([2, 4, 8, 10])

# Flash attention V2

In [220]:
Q_blocks = torch.split(Q, split_size_or_sections=q_block_size, dim=-2)
K_blocks = torch.split(K, split_size_or_sections=kv_block_size, dim=-2)
V_blocks = torch.split(V, split_size_or_sections=kv_block_size, dim=-2)
O_blocks = list(torch.split(O, split_size_or_sections=q_block_size, dim=-2)) # make it into a list, coz tuple assignment is not supported
m_blocks = torch.split(m, split_size_or_sections=q_block_size, dim=-2)
d_blocks = torch.split(d, split_size_or_sections=q_block_size, dim=-2)

for i in range(num_row_tiles):
    Qi = Q_blocks[i] # shape: (b, h, q_block_size, head_dim)

    oi = O_blocks[i] # shape: (b, h, q_block_size, head_dim)
    mi = m_blocks[i] # shape: (b, h, q_block_size, 1)
    di = d_blocks[i] # shape: (b, h, q_block_size, 1)

    for j in range(num_col_tiles):
        Kj = K_blocks[j] # shape: (b, h, kv_block_size, head_dim)
        Vj = V_blocks[j] # shape: (b, h, kv_block_size, head_dim)

        S_ij = Qi @ Kj.transpose(-1, -2) / math.sqrt(head_dim) # shape: (b, h, q_block_size, kv_block_size)
        m_ij = torch.max(S_ij, dim=-1, keepdim=True).values # shape: (b, h, q_block_size, 1)
        d_ij = torch.exp(S_ij-m_ij).sum(dim=-1, keepdim=True) # shape: (b, h, q_block_size, 1)
        P_ij = torch.exp(S_ij-m_ij) / d_ij # shape: (b, h, q_block_size, kv_block_size)
        o_ij = d_ij * P_ij @ Vj # (b, h, q_block_size, head_dim)

        new_mi = torch.maximum(mi, m_ij) # shape: (b, h, q_block_size, 1)
        new_di = di * torch.exp(mi - new_mi) + d_ij * torch.exp(m_ij - new_mi) # shape: (b, h, q_block_size, 1)
        new_oi = oi * torch.exp(mi - new_mi) + o_ij * torch.exp(m_ij - new_mi) # shape: (b, h, q_block_size, head_dim)

        mi = new_mi
        di = new_di
        oi = new_oi

    O_blocks[i] = oi / di # shape: (b, h, q_block_size, head_dim)

O = torch.cat(O_blocks, dim=-2) # shape: (b, h, q_len, head_dim)
print(O.shape)
assert torch.allclose(O, ground_truth, atol=1e-5)




torch.Size([2, 4, 8, 10])